chore: update pre-commit configuration

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -6,22 +6,28 @@ YELLOW='\033[0;33m'
 RED='\033[0;31m'
 NC='\033[0m' # No Color
 
-echo "${YELLOW}Running Test...${NC}"
+echo "${YELLOW}Running Jest tests...${NC}"
 npx jest --coverage
 if [ $? -ne 0 ]; then
   echo "${RED}Test failed. Coverage below Threshold %.${NC}"
   exit 1
 fi
-echo "${GREEN}Test completed with coverage >= Threshold %.${NC}"
+echo "${GREEN}Jest tests completed with coverage >= Threshold %.${NC}"
 
-echo "${YELLOW}Running ESLint...${NC}"
+echo "${YELLOW}Running ESLint checks...${NC}"
 npx eslint '**/*.{js,ts}'
+if [ $? -ne 0 ]; then
+  echo "${RED}ESLint found issues. Please fix the linting errors and try again.${NC}"
+  exit 1
+fi
+echo "${GREEN}ESLint checks completed successfully.${NC}"
 
-echo "${YELLOW}Running Prettier...${NC}"
+echo "${YELLOW}Running Prettier formatting check...${NC}"
 npx prettier --check '**/*.{js,ts}'
 if [ $? -ne 0 ]; then
   echo "${RED}Prettier check failed. Please format your code and try again.${NC}"
   exit 1
 fi
+echo "${GREEN}Prettier formatting check completed successfully.${NC}"
 
 echo "${GREEN}Pre-commit hook completed successfully.${NC}"
